import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className="scroll-smooth">
      <body className="max-w-5xl mx-auto bg-primary text-light-primary bg-texture">
        {children}
      </body>
    </html>
  );
}
